variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.

stages:
  - structure
  - engine
  - client
  - test
  - package

image: gitlab-edu.supsi.ch:5050/dti-isin/labingsw/common:ubuntu2404-cg

structure:
  stage: structure

  script:
    - '[ -d engine ] || exit 1'
    - '[ -d client ] || exit 1'
    - '[ -d test ] || exit 1'

  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

engine:
  stage: engine

  before_script:
    - 'cd engine'

  script:
    - 'make clean'
    - 'make'

  after_script:
    - 'cd ..'

  artifacts:
    paths:
      - engine/bin/Release/libengine.so
      - engine/bin/Debug/libengine.so

  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

client:
  stage: client

  before_script:
    - 'cd client'

  script:
    - 'make clean'
    - 'make'

  after_script:
    - 'cd ..'

  artifacts:
    paths:
      - client/bin/Release/*
      - client/bin/Debug/*

  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

test:
  stage: test

  before_script:
    - 'cd test'

  script:
    - 'make clean'
    - 'make'

  after_script:
    - 'cd ..'

  artifacts:
    paths:
      - test/bin/Release/*
      - test/bin/Debug/*

  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

package:
  stage: package

  before_script:
    - 'mkdir -p package'

  script:
    - 'tar -czvf demo.tar.gz demo/'
    - 'mv demo.tar.gz package/'

  artifacts:
    paths:
      - package/demo.tar.gz

  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"
